export const HISTORICAL_DRAFT_RESULTS = {
  "2019-20": [
    { overall: 1, round: 1, pickInRound: 1, team: "The Guns", player: "Zion Williamson", note: "", time: "10:00" },
    { overall: 2, round: 1, pickInRound: 2, team: "Drogalo Mountain Goats", player: "Ja Morant", note: "", time: "10:39" },
    { overall: 3, round: 1, pickInRound: 3, team: "The Rookies", player: "RJ Barrett", note: "", time: "10:42" },
    { overall: 4, round: 1, pickInRound: 4, team: "The Others", player: "Jarrett Culver", note: "", time: "13:45" },
    { overall: 5, round: 1, pickInRound: 5, team: "st.Helens Eruptions", player: "Coby White", note: "", time: "14:42" },
    { overall: 6, round: 1, pickInRound: 6, team: "Guruuu", player: "Darius Garland", note: "", time: "15:19" },
    { overall: 7, round: 1, pickInRound: 7, team: "The Others", player: "Cam Reddish", note: "", time: "15:32" },
    { overall: 8, round: 1, pickInRound: 8, team: "Salonika Devils", player: "Brandon Clarke", note: "", time: "16:04" },
    { overall: 9, round: 1, pickInRound: 9, team: "Donkey Rolls", player: "De'Andre Hunter", note: "", time: "18:02" },
    { overall: 10, round: 1, pickInRound: 10, team: "The Rookies", player: "Jaxson Hayes", note: "", time: "21:32" },
    { overall: 11, round: 1, pickInRound: 11, team: "The Others", player: "Zhaire Smith", note: "", time: "00:02" },
    { overall: 12, round: 1, pickInRound: 12, team: "Xanthi Ducks", player: "Kevon Looney", note: "", time: "10:00" },
    { overall: 13, round: 1, pickInRound: 13, team: "Guruuu", player: "Rui Hachimura", note: "", time: "12:53" },
    { overall: 14, round: 1, pickInRound: 14, team: "Samarina Dudenbros", player: "Cameron Johnson", note: "", time: "16:37" },
    { overall: 15, round: 1, pickInRound: 15, team: "Drogalo Mountain Goats", player: "Tyler Herro", note: "", time: "16:42" },
    { overall: 16, round: 1, pickInRound: 16, team: "Underdogs", player: "Grant Williams", note: "", time: "16:52" },
    { overall: 17, round: 1, pickInRound: 17, team: "Karafli Saita", player: "Nickeil Alexander-Walker", note: "", time: "16:59" },
    { overall: 18, round: 1, pickInRound: 18, team: "Pachiana NinjaBees", player: "Paul Millsap", note: "", time: "18:10" },
    { overall: 19, round: 1, pickInRound: 19, team: "The Bridgeburners", player: "Goga Bitadze", note: "", time: "18:14" },
    { overall: 20, round: 1, pickInRound: 20, team: "The Rookies", player: "Keldon Johnson", note: "", time: "21:26" },

    { overall: 21, round: 2, pickInRound: 1, team: "st.Helens Eruptions", player: "Malik Monk", note: "", time: "21:40" },
    { overall: 22, round: 2, pickInRound: 2, team: "The Bridgeburners", player: "Davis Bertans", note: "", time: "21:40" },
    { overall: 23, round: 2, pickInRound: 3, team: "Fighting Thaddeus", player: "Norman Powell", note: "", time: "21:41" },
    { overall: 24, round: 2, pickInRound: 4, team: "The Guns", player: "Tyus Jones", note: "", time: "21:44" },
    { overall: 25, round: 2, pickInRound: 5, team: "Pachiana NinjaBees", player: "Dwayne Bacon", note: "", time: "22:30" },
    { overall: 26, round: 2, pickInRound: 6, team: "Pachiana NinjaBees", player: "Troy Brown", note: "", time: "22:30" },
    { overall: 27, round: 2, pickInRound: 7, team: "Underdogs", player: "Daniel Gafford", note: "", time: "22:33" },
    { overall: 28, round: 2, pickInRound: 8, team: "Tsarlatans", player: "Luka Samanic", note: "", time: "22:36" },
    { overall: 29, round: 2, pickInRound: 9, team: "Retsiniakos 21", player: "Juan Hernangomez", note: "", time: "23:10" },
    { overall: 30, round: 2, pickInRound: 10, team: "Salonika Devils", player: "Alfonzo McKinnie", note: "", time: "23:20" },
    { overall: 31, round: 2, pickInRound: 11, team: "Donkey Rolls", player: "Noah Vonleh", note: "autopick", time: "11:21" },
    { overall: 32, round: 2, pickInRound: 12, team: "Kourayo Vallecano", player: "Alex Caruso", note: "", time: "11:23" },
    { overall: 33, round: 2, pickInRound: 13, team: "Kourayo Vallecano", player: "Ed Davis", note: "", time: "11:23" },
    { overall: 34, round: 2, pickInRound: 14, team: "purple fuzzy apache pirates", player: "Chris Boucher", note: "", time: "11:35" },
    { overall: 35, round: 2, pickInRound: 15, team: "Tsarlatans", player: "Willie Hernangomez", note: "", time: "12:15" },
    { overall: 36, round: 2, pickInRound: 16, team: "Retsiniakos 21", player: "Carsen Edwards", note: "", time: "12:17" },
    { overall: 37, round: 2, pickInRound: 17, team: "Fighting Thaddeus", player: "Jalen Brunson", note: "", time: "12:20" },
    { overall: 38, round: 2, pickInRound: 18, team: "Drogalo Mountain Goats", player: "Nemanja Bjelica", note: "", time: "13:31" },
    { overall: 39, round: 2, pickInRound: 19, team: "The Bridgeburners", player: "Bruce Brown", note: "", time: "13:36" },
    { overall: 40, round: 2, pickInRound: 20, team: "The Guns", player: "Matisse Thybulle", note: "", time: "13:39" },

    { overall: 41, round: 3, pickInRound: 1, team: "Xanthi Ducks", player: "Dillon Brooks", note: "", time: "13:47" },
    { overall: 42, round: 3, pickInRound: 2, team: "Samarina Dudenbros", player: "PJ Washington", note: "", time: "14:17" },
    { overall: 43, round: 3, pickInRound: 3, team: "Tsarlatans", player: "Sekou Doumbouya", note: "", time: "14:15" },
    { overall: 44, round: 3, pickInRound: 4, team: "purple fuzzy apache pirates", player: "Ish Smith", note: "", time: "14:27" },
    { overall: 45, round: 3, pickInRound: 5, team: "Samarina Dudenbros", player: "Bryn Forbes", note: "", time: "14:31" },
    { overall: 46, round: 3, pickInRound: 6, team: "Xanthi Ducks", player: "George Hill", note: "", time: "14:38" },
    { overall: 47, round: 3, pickInRound: 7, team: "Fighting Thaddeus", player: "Derrick Jones Jr.", note: "", time: "14:42" },
    { overall: 48, round: 3, pickInRound: 8, team: "Kourayo Vallecano", player: "PJ Tucker", note: "", time: "15:30" },
    { overall: 49, round: 3, pickInRound: 9, team: "purple fuzzy apache pirates", player: "Seth Curry", note: "", time: "16:14" },
    { overall: 50, round: 3, pickInRound: 10, team: "Karafli Saita", player: "Bruno Fernando", note: "", time: "16:20" },
    { overall: 51, round: 3, pickInRound: 11, team: "Steven Adams' Moustache", player: "DeMarre Carroll", note: "", time: "18:30" },
    { overall: 52, round: 3, pickInRound: 12, team: "Steven Adams' Moustache", player: "Ante Zizic", note: "", time: "18:30" },
    { overall: 53, round: 3, pickInRound: 13, team: "Steven Adams' Moustache", player: "Shabazz Napier", note: "", time: "18:30" },
  ],  "2018-19": [
  { overall: 1, round: 1, pickInRound: 1, team: "THE BRAZZERS BEATERS", player: "Justin Jackson", note: "", time: "" },
  { overall: 2, round: 1, pickInRound: 2, team: "The Underdogs", player: "Luka Doncic", note: "", time: "" },
  { overall: 3, round: 1, pickInRound: 3, team: "Brixton Guns", player: "Michael Porter Jr.", note: "", time: "" },
  { overall: 4, round: 1, pickInRound: 4, team: "Grand Theft Otto", player: "Kevin Knox II", note: "", time: "" },
  { overall: 5, round: 1, pickInRound: 5, team: "The Underdogs", player: "Trae Young", note: "", time: "" },
  { overall: 6, round: 1, pickInRound: 6, team: "Steven Adams' Moustache", player: "Jaren Jackson Jr.", note: "", time: "" },
  { overall: 7, round: 1, pickInRound: 7, team: "Brixton Guns", player: "De'Anthony Melton", note: "", time: "" },
  { overall: 8, round: 1, pickInRound: 8, team: "The Rookies", player: "Collin Sexton", note: "", time: "" },
  { overall: 9, round: 1, pickInRound: 9, team: "Grand Theft Otto", player: "Mo Bamba", note: "", time: "" },
  { overall: 10, round: 1, pickInRound: 10, team: "The Underdogs", player: "Wendell Carter Jr.", note: "", time: "" },
  { overall: 11, round: 1, pickInRound: 11, team: "Steven Adams' Moustache", player: "Zhaire Smith", note: "", time: "" },
  { overall: 12, round: 1, pickInRound: 12, team: "Donkey Rolls", player: "Chandler Hutchison", note: "", time: "" },
  { overall: 13, round: 1, pickInRound: 13, team: "THE BRAZZERS BEATERS", player: "Marvin Bagley III", note: "", time: "" },
  { overall: 14, round: 1, pickInRound: 14, team: "Grand Theft Otto", player: "Kevin Huerter", note: "", time: "" },
  { overall: 15, round: 1, pickInRound: 15, team: "Drogalo Mountain Goats", player: "Miles Bridges", note: "", time: "" },
  { overall: 16, round: 1, pickInRound: 16, team: "Georgetown SKG", player: "Shai Gilgeous-Alexander", note: "", time: "" },
  { overall: 17, round: 1, pickInRound: 17, team: "st.Helens Eruptions", player: "Robert Williams III", note: "", time: "" },
  { overall: 18, round: 1, pickInRound: 18, team: "The Underdogs", player: "Lonnie Walker IV", note: "", time: "" },
  { overall: 19, round: 1, pickInRound: 19, team: "purple fuzzy apache highheads", player: "Deandre Ayton", note: "", time: "" },
  { overall: 20, round: 1, pickInRound: 20, team: "Brixton Guns", player: "Elie Okobo", note: "", time: "" },
  { overall: 21, round: 2, pickInRound: 21, team: "Donkey Rolls", player: "Aaron Holiday", note: "", time: "" },
  { overall: 22, round: 2, pickInRound: 22, team: "The Bridgeburners", player: "Mitchell Robinson", note: "", time: "" },
  { overall: 23, round: 2, pickInRound: 23, team: "Kourayo Vallecano", player: "Josh Okogie", note: "", time: "" },
  { overall: 24, round: 2, pickInRound: 24, team: "The Others", player: "Grayson Allen", note: "", time: "" },
  { overall: 25, round: 2, pickInRound: 25, team: "(b)oldboy a revenge story", player: "Mikal Bridges", note: "", time: "" },
  ],
  "2017-18": [
  { overall: 1, round: 1, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Karl-Anthony Towns", note: "", time: "" },
  { overall: 2, round: 1, pickInRound: 2, team: "Tsoko Marokana", player: "Giannis Antetokounmpo", note: "", time: "" },
  { overall: 3, round: 1, pickInRound: 3, team: "Pachiana NinjaBees", player: "Anthony Davis", note: "", time: "" },
  { overall: 4, round: 1, pickInRound: 4, team: "Corto Maltesers", player: "James Harden", note: "", time: "" },
  { overall: 5, round: 1, pickInRound: 5, team: "st.Helens Eruptions", player: "Kevin Durant", note: "", time: "" },
  { overall: 6, round: 1, pickInRound: 6, team: "The Rookies", player: "Russell Westbrook", note: "", time: "" },
  { overall: 7, round: 1, pickInRound: 7, team: "Samarina DudenBros", player: "Kyrie Irving", note: "", time: "" },
  { overall: 8, round: 1, pickInRound: 8, team: "The Bridgeburners", player: "Stephen Curry", note: "", time: "" },
  { overall: 9, round: 1, pickInRound: 9, team: "Rebelion Naranja", player: "Nikola Jokic", note: "", time: "" },
  { overall: 10, round: 1, pickInRound: 10, team: "Brixton Guns", player: "Kawhi Leonard", note: "", time: "" },
  { overall: 11, round: 1, pickInRound: 11, team: "Kourayo Vallecano", player: "John Wall", note: "", time: "" },
  { overall: 12, round: 1, pickInRound: 12, team: "The Others", player: "Chris Paul", note: "", time: "" },
  { overall: 13, round: 1, pickInRound: 13, team: "Donkey Rolls", player: "LeBron James", note: "", time: "" },
  { overall: 14, round: 1, pickInRound: 14, team: "The walkinng dead", player: "DeMarcus Cousins", note: "", time: "" },
  { overall: 15, round: 1, pickInRound: 15, team: "Retsiniakos 21", player: "Rudy Gobert", note: "", time: "" },
  { overall: 16, round: 1, pickInRound: 16, team: "Arvyla BC", player: "Damian Lillard", note: "", time: "" },
  { overall: 17, round: 1, pickInRound: 17, team: "The Underdogs", player: "Myles Turner", note: "", time: "" },
  { overall: 18, round: 1, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Hassan Whiteside", note: "", time: "" },
  { overall: 19, round: 1, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Kristaps Porzingis", note: "", time: "" },
  { overall: 20, round: 1, pickInRound: 20, team: "Salonika Devils", player: "Kemba Walker", note: "", time: "" },
  { overall: 21, round: 2, pickInRound: 1, team: "Salonika Devils", player: "Jimmy Butler", note: "", time: "" },
  { overall: 22, round: 2, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Gordon Hayward", note: "", time: "" },
  { overall: 23, round: 2, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Blake Griffin", note: "", time: "" },
  { overall: 24, round: 2, pickInRound: 4, team: "The Underdogs", player: "CJ McCollum", note: "", time: "" },
  { overall: 25, round: 2, pickInRound: 5, team: "Arvyla BC", player: "Draymond Green", note: "", time: "" },
  { overall: 26, round: 2, pickInRound: 6, team: "Retsiniakos 21", player: "Dennis Schroder", note: "", time: "" },
  { overall: 27, round: 2, pickInRound: 7, team: "The walkinng dead", player: "Paul George", note: "", time: "" },
  { overall: 28, round: 2, pickInRound: 8, team: "Donkey Rolls", player: "Klay Thompson", note: "", time: "" },
  { overall: 29, round: 2, pickInRound: 9, team: "The Others", player: "Marc Gasol", note: "", time: "" },
  { overall: 30, round: 2, pickInRound: 10, team: "Kourayo Vallecano", player: "Mike Conley", note: "", time: "" },
  { overall: 31, round: 2, pickInRound: 11, team: "Brixton Guns", player: "Bradley Beal", note: "", time: "" },
  { overall: 32, round: 2, pickInRound: 12, team: "Rebelion Naranja", player: "Jusuf Nurkic", note: "", time: "" },
  { overall: 33, round: 2, pickInRound: 13, team: "The Bridgeburners", player: "Joel Embiid", note: "", time: "" },
  { overall: 34, round: 2, pickInRound: 14, team: "Samarina DudenBros", player: "Brook Lopez", note: "", time: "" },
  { overall: 35, round: 2, pickInRound: 15, team: "The Rookies", player: "Clint Capela", note: "", time: "" },
  { overall: 36, round: 2, pickInRound: 16, team: "st.Helens Eruptions", player: "Devin Booker", note: "", time: "" },
  { overall: 37, round: 2, pickInRound: 17, team: "Corto Maltesers", player: "DeAndre Jordan", note: "", time: "" },
  { overall: 38, round: 2, pickInRound: 18, team: "Pachiana NinjaBees", player: "Otto Porter Jr.", note: "", time: "" },
  { overall: 39, round: 2, pickInRound: 19, team: "Tsoko Marokana", player: "Kevin Love", note: "", time: "" },
  { overall: 40, round: 2, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Goran Dragic", note: "", time: "" },
  { overall: 41, round: 3, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Nicolas Batum", note: "", time: "" },
  { overall: 42, round: 3, pickInRound: 2, team: "Tsoko Marokana", player: "Nikola Vucevic", note: "", time: "" },
  { overall: 43, round: 3, pickInRound: 3, team: "Pachiana NinjaBees", player: "Kyle Lowry", note: "", time: "" },
  { overall: 44, round: 3, pickInRound: 4, team: "Corto Maltesers", player: "D'Angelo Russell", note: "", time: "" },
  { overall: 45, round: 3, pickInRound: 5, team: "st.Helens Eruptions", player: "Ben Simmons", note: "", time: "" },
  { overall: 46, round: 3, pickInRound: 6, team: "The Rookies", player: "DeMar DeRozan", note: "", time: "" },
  { overall: 47, round: 3, pickInRound: 7, team: "Samarina DudenBros", player: "Paul Millsap", note: "", time: "" },
  { overall: 48, round: 3, pickInRound: 8, team: "The Bridgeburners", player: "Khris Middleton", note: "", time: "" },
  { overall: 49, round: 3, pickInRound: 9, team: "Rebelion Naranja", player: "Andrew Wiggins", note: "", time: "" },
  { overall: 50, round: 3, pickInRound: 10, team: "Brixton Guns", player: "Eric Bledsoe", note: "", time: "" },
  { overall: 51, round: 3, pickInRound: 11, team: "Kourayo Vallecano", player: "Lonzo Ball", note: "", time: "" },
  { overall: 52, round: 3, pickInRound: 12, team: "The Others", player: "Ricky Rubio", note: "", time: "" },
  { overall: 53, round: 3, pickInRound: 13, team: "Donkey Rolls", player: "Andre Drummond", note: "", time: "" },
  { overall: 54, round: 3, pickInRound: 14, team: "The walkinng dead", player: "Al Horford", note: "", time: "" },
  { overall: 55, round: 3, pickInRound: 15, team: "Retsiniakos 21", player: "Dario Saric", note: "", time: "" },
  { overall: 56, round: 3, pickInRound: 16, team: "Arvyla BC", player: "Jonas Valanciunas", note: "", time: "" },
  { overall: 57, round: 3, pickInRound: 17, team: "The Underdogs", player: "Willy Hernangomez", note: "", time: "" },
  { overall: 58, round: 3, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Jeff Teague", note: "", time: "" },
  { overall: 59, round: 3, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Marcin Gortat", note: "", time: "" },
  { overall: 60, round: 3, pickInRound: 20, team: "Salonika Devils", player: "Dwight Howard", note: "", time: "" },
  { overall: 61, round: 4, pickInRound: 1, team: "Salonika Devils", player: "LaMarcus Aldridge", note: "", time: "" },
  { overall: 62, round: 4, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Dennis Smith Jr.", note: "", time: "" },
  { overall: 63, round: 4, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Jrue Holiday", note: "", time: "" },
  { overall: 64, round: 4, pickInRound: 4, team: "The Underdogs", player: "Julius Randle", note: "", time: "" },
  { overall: 65, round: 4, pickInRound: 5, team: "Arvyla BC", player: "Victor Oladipo", note: "", time: "" },
  { overall: 66, round: 4, pickInRound: 6, team: "Retsiniakos 21", player: "Evan Fournier", note: "", time: "" },
  { overall: 67, round: 4, pickInRound: 7, team: "The walkinng dead", player: "Markelle Fultz", note: "", time: "" },
  { overall: 68, round: 4, pickInRound: 8, team: "Donkey Rolls", player: "Serge Ibaka", note: "", time: "" },
  { overall: 69, round: 4, pickInRound: 9, team: "The Others", player: "Carmelo Anthony", note: "", time: "" },
  { overall: 70, round: 4, pickInRound: 10, team: "Kourayo Vallecano", player: "Harrison Barnes", note: "", time: "" },
  { overall: 71, round: 4, pickInRound: 11, team: "Brixton Guns", player: "Nerlens Noel", note: "", time: "" },
  { overall: 72, round: 4, pickInRound: 12, team: "Rebelion Naranja", player: "Elfrid Payton", note: "", time: "" },
  { overall: 73, round: 4, pickInRound: 13, team: "The Bridgeburners", player: "Robert Covington", note: "", time: "" },
  { overall: 74, round: 4, pickInRound: 14, team: "Samarina DudenBros", player: "Danilo Gallinari", note: "", time: "" },
  { overall: 75, round: 4, pickInRound: 15, team: "The Rookies", player: "Greg Monroe", note: "", time: "" },
  { overall: 76, round: 4, pickInRound: 16, team: "st.Helens Eruptions", player: "Steven Adams", note: "", time: "" },
  { overall: 77, round: 4, pickInRound: 17, team: "Corto Maltesers", player: "Tobias Harris", note: "", time: "" },
  { overall: 78, round: 4, pickInRound: 18, team: "Pachiana NinjaBees", player: "Eric Gordon", note: "", time: "" },
  { overall: 79, round: 4, pickInRound: 19, team: "Tsoko Marokana", player: "Marquese Chriss", note: "", time: "" },
  { overall: 80, round: 4, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Brandon Ingram", note: "", time: "" },
  { overall: 81, round: 5, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Jayson Tatum", note: "", time: "" },
  { overall: 82, round: 5, pickInRound: 2, team: "Tsoko Marokana", player: "Dion Waiters", note: "", time: "" },
  { overall: 83, round: 5, pickInRound: 3, team: "Pachiana NinjaBees", player: "Marcus Smart", note: "", time: "" },
  { overall: 84, round: 5, pickInRound: 4, team: "Corto Maltesers", player: "Willie Cauley-Stein", note: "", time: "" },
  { overall: 85, round: 5, pickInRound: 5, team: "st.Helens Eruptions", player: "Avery Bradley", note: "", time: "" },
  { overall: 86, round: 5, pickInRound: 6, team: "The Rookies", player: "James Johnson", note: "", time: "" },
  { overall: 87, round: 5, pickInRound: 7, team: "Samarina DudenBros", player: "Tim Hardaway Jr.", note: "", time: "" },
  { overall: 88, round: 5, pickInRound: 8, team: "The Bridgeburners", player: "Aaron Gordon", note: "", time: "" },
  { overall: 89, round: 5, pickInRound: 9, team: "Rebelion Naranja", player: "Kentavious Caldwell-Pope", note: "", time: "" },
  { overall: 90, round: 5, pickInRound: 10, team: "Brixton Guns", player: "Gary Harris", note: "", time: "" },
  { overall: 91, round: 5, pickInRound: 11, team: "Kourayo Vallecano", player: "Zach LaVine", note: "", time: "" },
  { overall: 92, round: 5, pickInRound: 12, team: "The Others", player: "Malcolm Brogdon", note: "", time: "" },
  { overall: 93, round: 5, pickInRound: 13, team: "Donkey Rolls", player: "Derrick Rose", note: "", time: "" },
  { overall: 94, round: 5, pickInRound: 14, team: "The walkinng dead", player: "Gorgui Dieng", note: "", time: "" },
  { overall: 95, round: 5, pickInRound: 15, team: "Retsiniakos 21", player: "Markieff Morris", note: "", time: "" },
  { overall: 96, round: 5, pickInRound: 16, team: "Arvyla BC", player: "Rudy Gay", note: "", time: "" },
  { overall: 97, round: 5, pickInRound: 17, team: "The Underdogs", player: "Patrick Beverley", note: "", time: "" },
  { overall: 98, round: 5, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Isaiah Thomas", note: "", time: "" },
  { overall: 99, round: 5, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Jabari Parker", note: "", time: "" },
  { overall: 100, round: 5, pickInRound: 20, team: "Salonika Devils", player: "Tristan Thompson", note: "", time: "" },
  { overall: 101, round: 6, pickInRound: 1, team: "Salonika Devils", player: "Enes Freedom", note: "", time: "" },
  { overall: 102, round: 6, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Buddy Hield", note: "", time: "" },
  { overall: 103, round: 6, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Derrick Favors", note: "", time: "" },
  { overall: 104, round: 6, pickInRound: 4, team: "The Underdogs", player: "Nikola Mirotic", note: "", time: "" },
  { overall: 105, round: 6, pickInRound: 5, team: "Arvyla BC", player: "Milos Teodosic", note: "", time: "" },
  { overall: 106, round: 6, pickInRound: 6, team: "Retsiniakos 21", player: "Mason Plumlee", note: "", time: "" },
  { overall: 107, round: 6, pickInRound: 7, team: "The walkinng dead", player: "Trevor Ariza", note: "", time: "" },
  { overall: 108, round: 6, pickInRound: 8, team: "Donkey Rolls", player: "Reggie Jackson", note: "", time: "" },
  { overall: 109, round: 6, pickInRound: 9, team: "The Others", player: "Patrick Patterson", note: "", time: "" },
  { overall: 110, round: 6, pickInRound: 10, team: "Kourayo Vallecano", player: "Jamal Murray", note: "", time: "" },
  { overall: 111, round: 6, pickInRound: 11, team: "Brixton Guns", player: "Jae Crowder", note: "", time: "" },
  { overall: 112, round: 6, pickInRound: 12, team: "Rebelion Naranja", player: "Wilson Chandler", note: "", time: "" },
  { overall: 113, round: 6, pickInRound: 13, team: "The Bridgeburners", player: "Jeremy Lin", note: "", time: "" },
  { overall: 114, round: 6, pickInRound: 14, team: "Samarina DudenBros", player: "Dwyane Wade", note: "", time: "" },
  { overall: 115, round: 6, pickInRound: 15, team: "The Rookies", player: "Frank Kaminsky", note: "", time: "" },
  { overall: 116, round: 6, pickInRound: 16, team: "st.Helens Eruptions", player: "George Hill", note: "", time: "" },
  { overall: 117, round: 6, pickInRound: 17, team: "Corto Maltesers", player: "Thaddeus Young", note: "", time: "" },
  { overall: 118, round: 6, pickInRound: 18, team: "Pachiana NinjaBees", player: "Robin Lopez", note: "", time: "" },
  { overall: 119, round: 6, pickInRound: 19, team: "Tsoko Marokana", player: "Tyler Johnson", note: "", time: "" },
  { overall: 120, round: 6, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Allen Crabbe", note: "", time: "" },
  { overall: 121, round: 7, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Kelly Olynyk", note: "", time: "" },
  { overall: 122, round: 7, pickInRound: 2, team: "Tsoko Marokana", player: "Jahlil Okafor", note: "", time: "" },
  { overall: 123, round: 7, pickInRound: 3, team: "Pachiana NinjaBees", player: "Rodney Hood", note: "", time: "" },
  { overall: 124, round: 7, pickInRound: 4, team: "Corto Maltesers", player: "T.J. Warren", note: "", time: "" },
  { overall: 125, round: 7, pickInRound: 5, team: "st.Helens Eruptions", player: "Rajon Rondo", note: "", time: "" },
  { overall: 126, round: 7, pickInRound: 6, team: "The Rookies", player: "Jordan Clarkson", note: "", time: "" },
  { overall: 127, round: 7, pickInRound: 7, team: "Samarina DudenBros", player: "Lou Williams", note: "", time: "" },
  { overall: 128, round: 7, pickInRound: 8, team: "The Bridgeburners", player: "Dewayne Dedmon", note: "", time: "" },
  { overall: 129, round: 7, pickInRound: 9, team: "Rebelion Naranja", player: "Justise Winslow", note: "", time: "" },
  { overall: 130, round: 7, pickInRound: 10, team: "Brixton Guns", player: "Cody Zeller", note: "", time: "" },
  { overall: 131, round: 7, pickInRound: 11, team: "Kourayo Vallecano", player: "Marvin Williams", note: "", time: "" },
  { overall: 132, round: 7, pickInRound: 12, team: "The Others", player: "Bismack Biyombo", note: "", time: "" },
  { overall: 133, round: 7, pickInRound: 13, team: "Donkey Rolls", player: "Bojan Bogdanovic", note: "", time: "" },
  { overall: 134, round: 7, pickInRound: 14, team: "The walkinng dead", player: "Kent Bazemore", note: "", time: "" },
  { overall: 135, round: 7, pickInRound: 15, team: "Retsiniakos 21", player: "Emmanuel Mudiay", note: "", time: "" },
  { overall: 136, round: 7, pickInRound: 16, team: "Arvyla BC", player: "JJ Redick", note: "", time: "" },
  { overall: 137, round: 7, pickInRound: 17, team: "The Underdogs", player: "Michael Beasley", note: "", time: "" },
  { overall: 138, round: 7, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Josh Jackson", note: "", time: "" },
  { overall: 139, round: 7, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Thon Maker", note: "", time: "" },
  { overall: 140, round: 7, pickInRound: 20, team: "Salonika Devils", player: "Austin Rivers", note: "", time: "" },
  { overall: 141, round: 8, pickInRound: 1, team: "Salonika Devils", player: "Tyreke Evans", note: "", time: "" },
  { overall: 142, round: 8, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Dejounte Murray", note: "", time: "" },
  { overall: 143, round: 8, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Seth Curry", note: "", time: "" },
  { overall: 144, round: 8, pickInRound: 4, team: "The Underdogs", player: "CJ Miles", note: "", time: "" },
  { overall: 145, round: 8, pickInRound: 5, team: "Arvyla BC", player: "Rondae Hollis Jefferson", note: "", time: "" },
  { overall: 146, round: 8, pickInRound: 6, team: "Retsiniakos 21", player: "Ryan Anderson", note: "", time: "" },
  { overall: 147, round: 8, pickInRound: 7, team: "The walkinng dead", player: "Will Barton", note: "", time: "" },
  { overall: 148, round: 8, pickInRound: 8, team: "Donkey Rolls", player: "Michael Kidd-Gilchrist", note: "", time: "" },
  { overall: 149, round: 8, pickInRound: 9, team: "The Others", player: "Danny Green", note: "", time: "" },
  { overall: 150, round: 8, pickInRound: 10, team: "Kourayo Vallecano", player: "JaMychal Green", note: "", time: "" },
  { overall: 151, round: 8, pickInRound: 11, team: "Brixton Guns", player: "Taurean Prince", note: "", time: "" },
  { overall: 152, round: 8, pickInRound: 12, team: "Rebelion Naranja", player: "Timofey Mozgov", note: "", time: "" },
  { overall: 153, round: 8, pickInRound: 13, team: "The Bridgeburners", player: "John Collins", note: "", time: "" },
  { overall: 154, round: 8, pickInRound: 14, team: "Samarina DudenBros", player: "Dirk Nowitzki", note: "", time: "" },
  { overall: 155, round: 8, pickInRound: 15, team: "The Rookies", player: "Zach Randolph", note: "", time: "" },
  { overall: 156, round: 8, pickInRound: 16, team: "st.Helens Eruptions", player: "Jaylen Brown", note: "", time: "" },
  { overall: 157, round: 8, pickInRound: 17, team: "Corto Maltesers", player: "T.J. McConnell", note: "", time: "" },
  { overall: 158, round: 8, pickInRound: 18, team: "Pachiana NinjaBees", player: "Kris Dunn", note: "", time: "" },
  { overall: 159, round: 8, pickInRound: 19, team: "Tsoko Marokana", player: "Wesley Matthews", note: "", time: "" },
  { overall: 160, round: 8, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Ersan Ilyasova", note: "", time: "" },
  { overall: 161, round: 9, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Lauri Markkanen", note: "", time: "" },
  { overall: 162, round: 9, pickInRound: 2, team: "Tsoko Marokana", player: "Pau Gasol", note: "", time: "" },
  { overall: 163, round: 9, pickInRound: 3, team: "Pachiana NinjaBees", player: "Marcus Morris Sr.", note: "", time: "" },
  { overall: 164, round: 9, pickInRound: 4, team: "Corto Maltesers", player: "Maurice Harkless", note: "", time: "" },
  { overall: 165, round: 9, pickInRound: 5, team: "st.Helens Eruptions", player: "Stanley Johnson", note: "", time: "" },
  { overall: 166, round: 9, pickInRound: 6, team: "The Rookies", player: "Joe Ingles", note: "", time: "" },
  { overall: 167, round: 9, pickInRound: 7, team: "Samarina DudenBros", player: "Darren Collison", note: "", time: "" },
  { overall: 168, round: 9, pickInRound: 8, team: "The Bridgeburners", player: "Caris LeVert", note: "", time: "" },
  { overall: 169, round: 9, pickInRound: 9, team: "Rebelion Naranja", player: "De'Aaron Fox", note: "", time: "" },
  { overall: 170, round: 9, pickInRound: 10, team: "Brixton Guns", player: "Richaun Holmes", note: "", time: "" },
  { overall: 171, round: 9, pickInRound: 11, team: "Kourayo Vallecano", player: "Alex Len", note: "", time: "" },
  { overall: 172, round: 9, pickInRound: 12, team: "The Others", player: "Taj Gibson", note: "", time: "" },
  { overall: 173, round: 9, pickInRound: 13, team: "Donkey Rolls", player: "Andre Iguodala", note: "", time: "" },
  { overall: 174, round: 9, pickInRound: 14, team: "The walkinng dead", player: "Courtney Lee", note: "", time: "" },
  { overall: 175, round: 9, pickInRound: 15, team: "Retsiniakos 21", player: "Tyler Ulis", note: "", time: "" },
  { overall: 176, round: 9, pickInRound: 16, team: "Arvyla BC", player: "Mike Muscala", note: "", time: "" },
  { overall: 177, round: 9, pickInRound: 17, team: "The Underdogs", player: "Norman Powell", note: "", time: "" },
  { overall: 178, round: 9, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Jarrett Allen", note: "", time: "" },
  { overall: 179, round: 9, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Brandon Jennings", note: "", time: "" },
  { overall: 180, round: 9, pickInRound: 20, team: "Salonika Devils", player: "Terrence Ross", note: "", time: "" },
  { overall: 181, round: 10, pickInRound: 1, team: "Salonika Devils", player: "Evan Turner", note: "", time: "" },
  { overall: 182, round: 10, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Zaza Pachulia", note: "", time: "" },
  { overall: 183, round: 10, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Larry Nance Jr.", note: "", time: "" },
  { overall: 184, round: 10, pickInRound: 4, team: "The Underdogs", player: "Malik Monk", note: "", time: "" },
  { overall: 185, round: 10, pickInRound: 5, team: "Arvyla BC", player: "Patty Mills", note: "", time: "" },
  { overall: 186, round: 10, pickInRound: 6, team: "Retsiniakos 21", player: "Kelly Oubre Jr.", note: "", time: "" },
  { overall: 187, round: 10, pickInRound: 7, team: "The walkinng dead", player: "Trevor Booker", note: "", time: "" },
  { overall: 188, round: 10, pickInRound: 8, team: "Donkey Rolls", player: "Al-Farouq Aminu", note: "", time: "" },
  { overall: 189, round: 10, pickInRound: 9, team: "The Others", player: "DeMarre Carroll", note: "", time: "" },
  { overall: 190, round: 10, pickInRound: 10, team: "Kourayo Vallecano", player: "Chandler Parsons", note: "", time: "" },
  { overall: 191, round: 10, pickInRound: 11, team: "Brixton Guns", player: "Skal Labissiere", note: "", time: "" },
  { overall: 192, round: 10, pickInRound: 12, team: "Rebelion Naranja", player: "Doug McDermott", note: "", time: "" },
  { overall: 193, round: 10, pickInRound: 13, team: "The Bridgeburners", player: "Bogdan Bogdanovic", note: "", time: "" },
  { overall: 194, round: 10, pickInRound: 14, team: "Samarina DudenBros", player: "Ivica Zubac", note: "", time: "" },
  { overall: 195, round: 10, pickInRound: 15, team: "The Rookies", player: "Justin Holiday", note: "", time: "" },
  { overall: 196, round: 10, pickInRound: 16, team: "st.Helens Eruptions", player: "Jakob Poeltl", note: "", time: "" },
  { overall: 197, round: 10, pickInRound: 17, team: "Corto Maltesers", player: "Frank Ntilikina", note: "", time: "" },
  { overall: 198, round: 10, pickInRound: 18, team: "Pachiana NinjaBees", player: "Nene", note: "", time: "" },
  { overall: 199, round: 10, pickInRound: 19, team: "Tsoko Marokana", player: "Cory Joseph", note: "", time: "" },
  { overall: 200, round: 10, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Ish Smith", note: "", time: "" },
  { overall: 201, round: 11, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Mario Hezonja", note: "", time: "" },
  { overall: 202, round: 11, pickInRound: 2, team: "Tsoko Marokana", player: "Jon Leuer", note: "", time: "" },
  { overall: 203, round: 11, pickInRound: 3, team: "Pachiana NinjaBees", player: "Jerami Grant", note: "", time: "" },
  { overall: 204, round: 11, pickInRound: 4, team: "Corto Maltesers", player: "Boban Marjanovic", note: "", time: "" },
  { overall: 205, round: 11, pickInRound: 5, team: "st.Helens Eruptions", player: "Kenneth Faried", note: "", time: "" },
  { overall: 206, round: 11, pickInRound: 6, team: "The Rookies", player: "Joe Johnson", note: "", time: "" },
  { overall: 207, round: 11, pickInRound: 7, team: "Samarina DudenBros", player: "JR Smith", note: "", time: "" },
  { overall: 208, round: 11, pickInRound: 8, team: "The Bridgeburners", player: "Ian Mahinmi", note: "", time: "" },
  { overall: 209, round: 11, pickInRound: 9, team: "Rebelion Naranja", player: "T.J. Leaf", note: "", time: "" },
  { overall: 210, round: 11, pickInRound: 10, team: "Brixton Guns", player: "Josh Richardson", note: "", time: "" },
  { overall: 211, round: 11, pickInRound: 11, team: "Kourayo Vallecano", player: "Tyson Chandler", note: "", time: "" },
  { overall: 212, round: 11, pickInRound: 12, team: "The Others", player: "Marco Belinelli", note: "", time: "" },
  { overall: 213, round: 11, pickInRound: 13, team: "Donkey Rolls", player: "Georgios Papagiannis", note: "", time: "" },
  { overall: 214, round: 11, pickInRound: 14, team: "The walkinng dead", player: "Jamal Crawford", note: "", time: "" },
  { overall: 215, round: 11, pickInRound: 15, team: "Retsiniakos 21", player: "Shabazz Muhammad", note: "", time: "" },
  { overall: 216, round: 11, pickInRound: 16, team: "Arvyla BC", player: "Bobby Portis", note: "", time: "" },
  { overall: 217, round: 11, pickInRound: 17, team: "The Underdogs", player: "Channing Frye", note: "", time: "" },
  { overall: 218, round: 11, pickInRound: 18, team: "Karafli Saita Reloaded", player: "Donovan Mitchell", note: "", time: "" },
  { overall: 219, round: 11, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Jonathon Simmons", note: "", time: "" },
  { overall: 220, round: 11, pickInRound: 20, team: "Salonika Devils", player: "Paul Zipser", note: "", time: "" },
  { overall: 221, round: 12, pickInRound: 1, team: "Salonika Devils", player: "Yogi Ferrell", note: "", time: "" },
  { overall: 222, round: 12, pickInRound: 2, team: "purple fuzzy apache hiheads", player: "Kyle Kuzma", note: "", time: "" },
  { overall: 223, round: 12, pickInRound: 3, team: "Karafli Saita Reloaded", player: "Jonathan Isaac", note: "", time: "" },
  { overall: 224, round: 12, pickInRound: 4, team: "The Underdogs", player: "Luke Kennard", note: "", time: "" },
  { overall: 225, round: 12, pickInRound: 5, team: "Arvyla BC", player: "Garrett Temple", note: "", time: "" },
  { overall: 226, round: 12, pickInRound: 6, team: "Retsiniakos 21", player: "Denzel Valentine", note: "", time: "" },
  { overall: 227, round: 12, pickInRound: 7, team: "The walkinng dead", player: "Justin Jackson", note: "", time: "" },
  { overall: 228, round: 12, pickInRound: 8, team: "Donkey Rolls", player: "Ed Davis", note: "", time: "" },
  { overall: 229, round: 12, pickInRound: 9, team: "The Others", player: "Lance Stephenson", note: "", time: "" },
  { overall: 230, round: 12, pickInRound: 10, team: "Kourayo Vallecano", player: "Domantas Sabonis", note: "", time: "" },
  { overall: 231, round: 12, pickInRound: 11, team: "Brixton Guns", player: "Tony Snell", note: "", time: "" },
  { overall: 232, round: 12, pickInRound: 12, team: "Rebelion Naranja", player: "D.J. Wilson", note: "", time: "" },
  { overall: 233, round: 12, pickInRound: 13, team: "The Bridgeburners", player: "Matthew Dellavedova", note: "", time: "" },
  { overall: 234, round: 12, pickInRound: 14, team: "Samarina DudenBros", player: "Brandan Wright", note: "", time: "" },
  { overall: 235, round: 12, pickInRound: 15, team: "The Rookies", player: "Ben McLemore", note: "", time: "" },
  { overall: 236, round: 12, pickInRound: 16, team: "st.Helens Eruptions", player: "Kyle O'Quinn", note: "", time: "" },
  { overall: 237, round: 12, pickInRound: 17, team: "Corto Maltesers", player: "Davis Bertans", note: "", time: "" },
  { overall: 238, round: 12, pickInRound: 18, team: "Pachiana NinjaBees", player: "Wayne Selden", note: "", time: "" },
  { overall: 239, round: 12, pickInRound: 19, team: "Tsoko Marokana", player: "Spencer Dinwiddie", note: "", time: "" },
  { overall: 240, round: 12, pickInRound: 20, team: "Drogalo Mountain Goats", player: "Tyler Dorsey", note: "", time: "" },
  { overall: 241, round: 13, pickInRound: 1, team: "Drogalo Mountain Goats", player: "Dragan Bender", note: "", time: "" },
  { overall: 242, round: 13, pickInRound: 2, team: "Tsoko Marokana", player: "Malcolm Delaney", note: "", time: "" },
  { overall: 243, round: 13, pickInRound: 3, team: "Pachiana NinjaBees", player: "Bam Adebayo", note: "", time: "" },
  { overall: 244, round: 13, pickInRound: 4, team: "Corto Maltesers", player: "Darius Miller", note: "", time: "" },
  { overall: 245, round: 13, pickInRound: 5, team: "st.Helens Eruptions", player: "Terry Rozier", note: "", time: "" },
  { overall: 246, round: 13, pickInRound: 6, team: "The Rookies", player: "Monta Ellis", note: "", time: "" },
  { overall: 247, round: 13, pickInRound: 7, team: "Samarina DudenBros", player: "P.J. Tucker", note: "", time: "" },
  { overall: 248, round: 13, pickInRound: 8, team: "The Bridgeburners", player: "Alan Williams", note: "", time: "" },
  { overall: 249, round: 13, pickInRound: 9, team: "Rebelion Naranja", player: "Jordan Crawford", note: "", time: "" },
  { overall: 250, round: 13, pickInRound: 10, team: "Brixton Guns", player: "Jameer Nelson", note: "", time: "" },
  { overall: 251, round: 13, pickInRound: 11, team: "Kourayo Vallecano", player: "Tony Allen", note: "", time: "" },
  { overall: 252, round: 13, pickInRound: 12, team: "The Others", player: "Kyle Anderson", note: "", time: "" },
  { overall: 253, round: 13, pickInRound: 13, team: "Donkey Rolls", player: "Andrew Harrison", note: "", time: "" },
  { overall: 254, round: 13, pickInRound: 14, team: "The walkinng dead", player: "Brandon Knight", note: "", time: "" },
  { overall: 255, round: 13, pickInRound: 15, team: "Retsiniakos 21", player: "Ike Anigbogu", note: "", time: "" },
  { overall: 256, round: 13, pickInRound: 16, team: "Arvyla BC", player: "JaVale McGee", note: "", time: "" },
  { overall: 257, round: 13, pickInRound: 17, team: "The Underdogs", player: "Zach Collins", note: "", time: "" },
  { overall: 258, round: 13, pickInRound: 18, team: "Karafli Saita Reloaded", player: "E'Twaun Moore", note: "", time: "" },
  { overall: 259, round: 13, pickInRound: 19, team: "purple fuzzy apache hiheads", player: "Ian Clark", note: "", time: "" },
  { overall: 260, round: 13, pickInRound: 20, team: "Salonika Devils", player: "Glenn Robinson III", note: "", time: "" },
],
}