export const HISTORICAL_DRAFT_RESULTS = {
  "2019-20": [
    { overall: 1, round: 1, pickInRound: 1, team: "The Guns", player: "Zion Williamson", note: "", time: "10:00" },
    { overall: 2, round: 1, pickInRound: 2, team: "Drogalo Mountain Goats", player: "Ja Morant", note: "", time: "10:39" },
    { overall: 3, round: 1, pickInRound: 3, team: "The Rookies", player: "RJ Barrett", note: "", time: "10:42" },
    { overall: 4, round: 1, pickInRound: 4, team: "The Others", player: "Jarrett Culver", note: "", time: "13:45" },
    { overall: 5, round: 1, pickInRound: 5, team: "st.Helens Eruptions", player: "Coby White", note: "", time: "14:42" },
    { overall: 6, round: 1, pickInRound: 6, team: "Guruuu", player: "Darius Garland", note: "", time: "15:19" },
    { overall: 7, round: 1, pickInRound: 7, team: "The Others", player: "Cam Reddish", note: "", time: "15:32" },
    { overall: 8, round: 1, pickInRound: 8, team: "Salonika Devils", player: "Brandon Clarke", note: "", time: "16:04" },
    { overall: 9, round: 1, pickInRound: 9, team: "Donkey Rolls", player: "De'Andre Hunter", note: "", time: "18:02" },
    { overall: 10, round: 1, pickInRound: 10, team: "The Rookies", player: "Jaxson Hayes", note: "", time: "21:32" },
    { overall: 11, round: 1, pickInRound: 11, team: "The Others", player: "Zhaire Smith", note: "", time: "00:02" },
    { overall: 12, round: 1, pickInRound: 12, team: "Xanthi Ducks", player: "Kevon Looney", note: "", time: "10:00" },
    { overall: 13, round: 1, pickInRound: 13, team: "Guruuu", player: "Rui Hachimura", note: "", time: "12:53" },
    { overall: 14, round: 1, pickInRound: 14, team: "Samarina Dudenbros", player: "Cameron Johnson", note: "", time: "16:37" },
    { overall: 15, round: 1, pickInRound: 15, team: "Drogalo Mountain Goats", player: "Tyler Herro", note: "", time: "16:42" },
    { overall: 16, round: 1, pickInRound: 16, team: "Underdogs", player: "Grant Williams", note: "", time: "16:52" },
    { overall: 17, round: 1, pickInRound: 17, team: "Karafli Saita", player: "Nickeil Alexander-Walker", note: "", time: "16:59" },
    { overall: 18, round: 1, pickInRound: 18, team: "Pachiana NinjaBees", player: "Paul Millsap", note: "", time: "18:10" },
    { overall: 19, round: 1, pickInRound: 19, team: "The Bridgeburners", player: "Goga Bitadze", note: "", time: "18:14" },
    { overall: 20, round: 1, pickInRound: 20, team: "The Rookies", player: "Keldon Johnson", note: "", time: "21:26" },

    { overall: 21, round: 2, pickInRound: 1, team: "st.Helens Eruptions", player: "Malik Monk", note: "", time: "21:40" },
    { overall: 22, round: 2, pickInRound: 2, team: "The Bridgeburners", player: "Davis Bertans", note: "", time: "21:40" },
    { overall: 23, round: 2, pickInRound: 3, team: "Fighting Thaddeus", player: "Norman Powell", note: "", time: "21:41" },
    { overall: 24, round: 2, pickInRound: 4, team: "The Guns", player: "Tyus Jones", note: "", time: "21:44" },
    { overall: 25, round: 2, pickInRound: 5, team: "Pachiana NinjaBees", player: "Dwayne Bacon", note: "", time: "22:30" },
    { overall: 26, round: 2, pickInRound: 6, team: "Pachiana NinjaBees", player: "Troy Brown", note: "", time: "22:30" },
    { overall: 27, round: 2, pickInRound: 7, team: "Underdogs", player: "Daniel Gafford", note: "", time: "22:33" },
    { overall: 28, round: 2, pickInRound: 8, team: "Tsarlatans", player: "Luka Samanic", note: "", time: "22:36" },
    { overall: 29, round: 2, pickInRound: 9, team: "Retsiniakos 21", player: "Juan Hernangomez", note: "", time: "23:10" },
    { overall: 30, round: 2, pickInRound: 10, team: "Salonika Devils", player: "Alfonzo McKinnie", note: "", time: "23:20" },
    { overall: 31, round: 2, pickInRound: 11, team: "Donkey Rolls", player: "Noah Vonleh", note: "autopick", time: "11:21" },
    { overall: 32, round: 2, pickInRound: 12, team: "Kourayo Vallecano", player: "Alex Caruso", note: "", time: "11:23" },
    { overall: 33, round: 2, pickInRound: 13, team: "Kourayo Vallecano", player: "Ed Davis", note: "", time: "11:23" },
    { overall: 34, round: 2, pickInRound: 14, team: "purple fuzzy apache pirates", player: "Chris Boucher", note: "", time: "11:35" },
    { overall: 35, round: 2, pickInRound: 15, team: "Tsarlatans", player: "Willie Hernangomez", note: "", time: "12:15" },
    { overall: 36, round: 2, pickInRound: 16, team: "Retsiniakos 21", player: "Carsen Edwards", note: "", time: "12:17" },
    { overall: 37, round: 2, pickInRound: 17, team: "Fighting Thaddeus", player: "Jalen Brunson", note: "", time: "12:20" },
    { overall: 38, round: 2, pickInRound: 18, team: "Drogalo Mountain Goats", player: "Nemanja Bjelica", note: "", time: "13:31" },
    { overall: 39, round: 2, pickInRound: 19, team: "The Bridgeburners", player: "Bruce Brown", note: "", time: "13:36" },
    { overall: 40, round: 2, pickInRound: 20, team: "The Guns", player: "Matisse Thybulle", note: "", time: "13:39" },

    { overall: 41, round: 3, pickInRound: 1, team: "Xanthi Ducks", player: "Dillon Brooks", note: "", time: "13:47" },
    { overall: 42, round: 3, pickInRound: 2, team: "Samarina Dudenbros", player: "PJ Washington", note: "", time: "14:17" },
    { overall: 43, round: 3, pickInRound: 3, team: "Tsarlatans", player: "Sekou Doumbouya", note: "", time: "14:15" },
    { overall: 44, round: 3, pickInRound: 4, team: "purple fuzzy apache pirates", player: "Ish Smith", note: "", time: "14:27" },
    { overall: 45, round: 3, pickInRound: 5, team: "Samarina Dudenbros", player: "Bryn Forbes", note: "", time: "14:31" },
    { overall: 46, round: 3, pickInRound: 6, team: "Xanthi Ducks", player: "George Hill", note: "", time: "14:38" },
    { overall: 47, round: 3, pickInRound: 7, team: "Fighting Thaddeus", player: "Derrick Jones Jr.", note: "", time: "14:42" },
    { overall: 48, round: 3, pickInRound: 8, team: "Kourayo Vallecano", player: "PJ Tucker", note: "", time: "15:30" },
    { overall: 49, round: 3, pickInRound: 9, team: "purple fuzzy apache pirates", player: "Seth Curry", note: "", time: "16:14" },
    { overall: 50, round: 3, pickInRound: 10, team: "Karafli Saita", player: "Bruno Fernando", note: "", time: "16:20" },
    { overall: 51, round: 3, pickInRound: 11, team: "Steven Adams' Moustache", player: "DeMarre Carroll", note: "", time: "18:30" },
    { overall: 52, round: 3, pickInRound: 12, team: "Steven Adams' Moustache", player: "Ante Zizic", note: "", time: "18:30" },
    { overall: 53, round: 3, pickInRound: 13, team: "Steven Adams' Moustache", player: "Shabazz Napier", note: "", time: "18:30" },
  ],
}