export const SIDELEAGUES = [
     {
    key: "nbarrwstoi-playoffs-2026",
    name: "NBArrwstoi Playoffs",
    seasonLabel: "2025-26",
    leagueId: "hghqs214mo5iixxy",
    period: 1,
    description: "NBArrwstoi Playoffs Special",
    view: "final_standings",
  },
    {
  key: "euroleague-2025-26",
  name: "Euroleague",
  seasonLabel: "2025-26",
  view: "sheet_league",
  description: "Euroleague sideleague.",
  resultsCsvUrl:
    "https://docs.google.com/spreadsheets/d/1tBVOmiG7X_Z3RSfpgOrbQrNkEE4E-j4pVrz8a8oibrQ/export?format=csv&gid=0",
  draftCsvUrl:
    "https://docs.google.com/spreadsheets/d/1ut1Pt_7PEXLvk-0CTZD_9Hc46nr0WQxf-ifXgpzKBfM/export?format=csv&gid=359349027",
  rostersCsvUrl:
    "https://docs.google.com/spreadsheets/d/1ut1Pt_7PEXLvk-0CTZD_9Hc46nr0WQxf-ifXgpzKBfM/export?format=csv&gid=0",
    },
    {
        key: "konti-yearly-2024",
        name: "KONTI Yearly",
        seasonLabel: "2023-24",
        leagueId: "t6ycigy6lmzy3wku",
        period: 1,
        playoffs: true,
        playoffStartPeriod: 19,
        description: "Yearly SideLeague",
        view: "final_standings",
        },
  {
    key: "asg-nbarrwstoi-all-star-2024",
    name: "ASG NBArrwstoi All Star",
    seasonLabel: "2023-24",
    leagueId: "wpdqnosflsevb5ee",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North All Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-rising-star-2024",
    name: "ASG NBArrwstoi Rising Star",
    seasonLabel: "2023-24",
    leagueId: "or0icac4lsevb7nh",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North Rising Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-3pts-contest-2024",
    name: "ASG NBArrwstoi 3pts contest",
    seasonLabel: "2023-24",
    leagueId: "608b1juglsevaykb",
    period: 1,
    description: "3-point contest final standings.",
    view: "final_standings",
  },
  {
    key: "asg-nbarrwstoi-veteran-star-2024",
    name: "ASG NBArrwstoi Veteran Star",
    seasonLabel: "2023-24",
    leagueId: "1k4wzr7hlsevba9g",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North Veteran Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-3-on-3-2024",
    name: "ASG NBArrwstoi 3-on-3",
    seasonLabel: "2023-24",
    leagueId: "q45whltylsevavsh",
    period: 1,
    description: "3-on-3 final standings.",
    view: "final_standings",
  },
 {
    key: "nbarrwstoi-playoffs-2023",
    name: "NBArrwstoi Playoffs",
    seasonLabel: "2022-23",
    leagueId: "j0595suclfqxenxj",
    period: 1,
    description: "NBArrwstoi Playoffs Special",
    view: "final_standings",
  },
  {
    key: "asg-nbarrwstoi-all-star-2023",
    name: "ASG NBArrwstoi All Star",
    seasonLabel: "2022-23",
    leagueId: "p7w9kbr4le03ckxd",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North All Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-rising-star-2023",
    name: "ASG NBArrwstoi Rising Star",
    seasonLabel: "2022-23",
    leagueId: "23456du8le03lkls",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North Rising Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-3pts-contest-2023",
    name: "ASG NBArrwstoi 3pts contest",
    seasonLabel: "2022-23",
    leagueId: "kkv6eog5le03x8qo",
    period: 1,
    description: "3-point contest final standings.",
    view: "final_standings",
  },
  {
    key: "asg-nbarrwstoi-veteran-star-2023",
    name: "ASG NBArrwstoi Veteran Star",
    seasonLabel: "2022-23",
    leagueId: "30he76xxle03ozaw",
    period: 1,
    teams: ["South", "North"],
    description: "South vs North Veteran Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-3-on-3-2023",
    name: "ASG NBArrwstoi 3-on-3",
    seasonLabel: "2022-23",
    leagueId: "ooofafvrle05ddu8",
    period: 1,
    description: "3-on-3 final standings.",
    view: "final_standings",
  },

  {
    key: "asg-nbarrwstoi-all-star-2022",
    name: "ASG NBArrwstoi All Star",
    seasonLabel: "2021-22",
    leagueId: "zaihibm3kzi5f12y",
    period: 1,
    teams: ["White", "Blue"],
    description: "White vs Blue All Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-rising-star-2022",
    name: "ASG NBArrwstoi Rising Star",
    seasonLabel: "2021-22",
    leagueId: "4imjcwoakzi6qqe9",
    period: 1,
    teams: ["White", "Blue"],
    description: "White vs Blue Rising Star side league.",
    view: "matchup_rosters",
  },
  {
    key: "asg-nbarrwstoi-3pts-contest-2022",
    name: "ASG NBArrwstoi 3pts contest",
    seasonLabel: "2021-22",
    leagueId: "z5npzkodkzibwuut",
    period: 1,
    description: "3-point contest final standings.",
    view: "final_standings",
  },
  {
    key: "asg-nbarrwstoi-3-on-3-2022",
    name: "ASG NBArrwstoi 3-on-3",
    seasonLabel: "2021-22",
    leagueId: "ooofafvrle05ddu8",
    period: 1,
    description: "3-on-3 final standings.",
    view: "final_standings",
  },
  {
    key: "nbarrwstoi-playoffs-2022",
    name: "NBArrwstoi Playoffs",
    seasonLabel: "2021-22",
    leagueId: "gzsyqblhl1ckrqgt",
    period: 1,
    description: "NBArrwstoi Playoffs Special",
    view: "final_standings",
  },
  {
    key: "nbarrwstoi-playoffs-2021",
    name: "NBArrwstoi Playoffs",
    seasonLabel: "2020-21",
    leagueId: "khxqk4u2kp6tu7es",
    period: 1,
    description: "NBArrwstoi Playoffs Special",
    view: "final_standings",
  },
   {
    key: "nbarrwstoi-playoffs-2019",
    name: "NBArrwstoi Playoffs",
    seasonLabel: "2018-19",
    leagueId: "djhqozjgjtzqpq1b",
    period: 1,
    description: "Pilot Fantrax League",
    view: "final_standings",
  },
]

export function getSideleagueByKey(key) {
  return SIDELEAGUES.find((item) => item.key === key) || null
}